/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikum2;

import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class hitung extends javax.swing.JFrame {

    /**
     * Creates new form hitung
     */
    public hitung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Nim = new javax.swing.JTextField();
        Nilaitgs = new javax.swing.JTextField();
        Nilaikuis = new javax.swing.JTextField();
        Nilaiuts = new javax.swing.JTextField();
        Nilaiuas = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        outNama = new javax.swing.JLabel();
        outNim = new javax.swing.JLabel();
        outRerata = new javax.swing.JLabel();
        outGrade = new javax.swing.JLabel();
        outKet = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        Hitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Menghitung Nilai Mahasiswa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(104, 11, 243, 32);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 82, 27);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Nilai Tugas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 160, 82, 27);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Nilai Kuis");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 200, 82, 27);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("NIM");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 120, 82, 27);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Nilai UTS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 240, 82, 27);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Nilai UAS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 280, 82, 27);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(110, 80, 180, 27);

        Nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NimActionPerformed(evt);
            }
        });
        getContentPane().add(Nim);
        Nim.setBounds(110, 120, 180, 27);

        Nilaitgs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NilaitgsActionPerformed(evt);
            }
        });
        getContentPane().add(Nilaitgs);
        Nilaitgs.setBounds(110, 160, 180, 27);

        Nilaikuis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NilaikuisActionPerformed(evt);
            }
        });
        getContentPane().add(Nilaikuis);
        Nilaikuis.setBounds(110, 200, 180, 27);

        Nilaiuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NilaiutsActionPerformed(evt);
            }
        });
        getContentPane().add(Nilaiuts);
        Nilaiuts.setBounds(110, 280, 180, 27);

        Nilaiuas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NilaiuasActionPerformed(evt);
            }
        });
        getContentPane().add(Nilaiuas);
        Nilaiuas.setBounds(110, 240, 180, 30);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel2.setToolTipText("");
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 62, 290, 260);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Output", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel3.setLayout(null);

        outNama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(outNama);
        outNama.setBounds(130, 20, 160, 27);

        outNim.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(outNim);
        outNim.setBounds(130, 60, 160, 27);

        outRerata.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(outRerata);
        outRerata.setBounds(130, 100, 160, 27);

        outGrade.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(outGrade);
        outGrade.setBounds(130, 140, 160, 27);

        outKet.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(outKet);
        outKet.setBounds(130, 180, 160, 27);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setText("Keterangan   :");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 180, 82, 27);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Grade           :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 140, 82, 27);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Rerata          :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 100, 82, 27);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("NIM            :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 60, 82, 27);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setText("Nama           :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 20, 82, 27);

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel3.add(Reset);
        Reset.setBounds(210, 220, 80, 30);

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        jPanel3.add(Simpan);
        Simpan.setBounds(120, 220, 80, 30);

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel3.add(Hitung);
        Hitung.setBounds(30, 220, 80, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(320, 60, 300, 260);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 340);

        setBounds(0, 0, 654, 379);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void NimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NimActionPerformed

    private void NilaitgsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NilaitgsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NilaitgsActionPerformed

    private void NilaikuisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NilaikuisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NilaikuisActionPerformed

    private void NilaiutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NilaiutsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NilaiutsActionPerformed

    private void NilaiuasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NilaiuasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NilaiuasActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        
        String nama = Nama.getText();
        String nim = Nim.getText();
        if (Nilaitgs.getText().isEmpty()||Nilaikuis.getText().isEmpty()|| Nilaiuts.getText().isEmpty()||Nilaiuas.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Maaf , form masih kosong");
        }
        else {
            Double rerata = (Double.parseDouble(Nilaitgs.getText())+
Double.parseDouble(Nilaikuis.getText())+
                    Double.parseDouble(Nilaiuts.getText())+Double.parseDouble (Nilaiuas.getText()))/4;
            outRerata.setText(rerata.toString().substring(0,5));
            outNama.setText(nama);
            outNim.setText(nim);
        }
        //Untuk grade
        Double a = Double.parseDouble(outRerata.getText());
        char grade=' ';
        if (a >= 90.00){
            grade = 'A';
            outGrade.setText(""+grade);
        }
        else if (a >= 80.00 && a <=89.00 ){
            grade ='B';
            outGrade.setText(""+grade);
        }
        else if (a >= 70.00 && a <= 79.00){
            grade = 'C';
            outGrade.setText(""+grade);
        }
        else if (a >= 40.00 && a <= 69.00){
            grade = 'D';
            outGrade.setText(""+grade);
        }
        else if (a <= 39.00){
            grade = 'E';
            outGrade.setText(""+grade);
        }
        //keterangan
        if (grade == 'A' || grade =='B' || grade == 'C'){
           
            outKet.setText("Dinyatakan Lulus");
        }
        else {
            outKet.setText("Dinyatakan Tidak Lulus");
        }
    }//GEN-LAST:event_HitungActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here
        
        Nama.setText(null);
        Nim.setText(null);
        Nilaitgs.setText(null);
        Nilaikuis.setText(null);
        Nilaiuts.setText(null);
        Nilaiuas.setText(null);
        outNama.setText(null);
        outNim.setText(null);
        outRerata.setText(null);
        outGrade.setText(null);
        outKet.setText(null);
    }//GEN-LAST:event_ResetActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        
         try {
            BufferedWriter simpan = new BufferedWriter (new FileWriter("nilai.txt"));
            String hasil = "Nama : \t"+outNama.getText()+"\n"+
                            "Nim : \t"+outNim.getText()+"\n"+
                            "Rata-rata :\t"+outRerata.getText()+"\n"+
                            "Grade : \t"+outGrade.getText()+"\n"+
                            "Keterangan : \t"+outKet.getText();
            simpan.write(hasil);
            JOptionPane.showMessageDialog(null,"Data berhasil disimpan");
            simpan.close();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null ,e);
        }
    }//GEN-LAST:event_SimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hitung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hitung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hitung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hitung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hitung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nilaikuis;
    private javax.swing.JTextField Nilaitgs;
    private javax.swing.JTextField Nilaiuas;
    private javax.swing.JTextField Nilaiuts;
    private javax.swing.JTextField Nim;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel outGrade;
    private javax.swing.JLabel outKet;
    private javax.swing.JLabel outNama;
    private javax.swing.JLabel outNim;
    private javax.swing.JLabel outRerata;
    // End of variables declaration//GEN-END:variables
}
